services:
  prefect-server:
    build: .
    restart: always
    ports:
      - 4200:4200
    environment:
      PREFECT_SERVER_API_HOST: 0.0.0.0
    command: ["prefect", "server", "start"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/api/health"]
      interval: 10s
      timeout: 2s

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - mongo-data:/data/db 

  data-sync:
    build: .
    environment:
      PREFECT_API_URL: http://prefect-server:4200/api
    env_file:
      - .env
    depends_on:
      prefect-server:
        condition: service_healthy
    restart: always
    volumes:
      - ./src:/src/
    command: ["python", "update_data.py"]

  ui:
    build: .
    env_file:
      - .env
    ports:
      - 8501:8501
    depends_on:
      prefect-server:
        condition: service_healthy
    restart: always
    volumes:
      - ./src:/src/
    command: ["streamlit", "run", "ui.py", "--server.port=8501", "--server.address=0.0.0.0"]

volumes:
  mongo-data: {}